import { StyleSheet } from "react-native";

export const colors = {
  primary: "#FF6B35",
  secondary: "#4ECDC4",
  accent: "#FFE66D",
  danger: "#FF6B6B",
  background: "#FFF8E1",
  card: "#FFF",
  text: "#000",
  textLight: "#666",
  border: "#000",
  borderLight: "#E0E0E0",
};

export const sharedStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.primary,
    paddingVertical: 40,
    paddingHorizontal: 20,
    borderRadius: 15,
    borderWidth: 4,
    borderColor: colors.border,
    marginBottom: 30,
    alignItems: "center",
    position: "relative",
    shadowColor: colors.border,
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
  },
  comicBurst: {
    position: "absolute",
    top: -20,
    right: -20,
    width: 80,
    height: 80,
    backgroundColor: colors.accent,
    transform: [{ rotate: "20deg" }],
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: colors.border,
    borderRadius: 12,
  },
  burstText: {
    fontSize: 16,
    fontWeight: "black",
    color: colors.text,
    transform: [{ rotate: "-20deg" }],
  },
  title: {
    fontSize: 32,
    fontWeight: "black",
    color: colors.card,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.accent,
  },
  formCard: {
    backgroundColor: colors.card,
    borderRadius: 15,
    borderWidth: 4,
    borderColor: colors.border,
    padding: 25,
    marginBottom: 25,
    shadowColor: colors.border,
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
  },
  formTitle: {
    fontSize: 20,
    fontWeight: "black",
    color: colors.text,
    marginBottom: 20,
    backgroundColor: colors.secondary,
    paddingHorizontal: 15,
    paddingVertical: 8,
    alignSelf: "flex-start",
    borderWidth: 2,
    borderColor: colors.border,
    transform: [{ rotate: "-1deg" }],
  },
  inputWrapper: {
    marginBottom: 18,
  },
  inputLabel: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  inputLabelText: {
    fontSize: 12,
    fontWeight: "black",
    color: colors.primary,
    marginLeft: 6,
    textTransform: "uppercase",
  },
  input: {
    width: "100%",
    borderWidth: 3,
    borderColor: colors.border,
    padding: 14,
    borderRadius: 10,
    backgroundColor: colors.background,
    fontSize: 16,
    fontWeight: "500",
    color: colors.text,
  },
  button: {
    width: "100%",
    backgroundColor: colors.danger,
    paddingVertical: 16,
    borderRadius: 12,
    marginTop: 10,
    borderWidth: 4,
    borderColor: colors.border,
    shadowColor: colors.border,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: colors.card,
    fontSize: 18,
    fontWeight: "black",
    textAlign: "center",
    textTransform: "uppercase",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
    padding: 20,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
    padding: 40,
  },
});
